[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
myepicproject = "5jYr5nueJ2AfxSGh9qZMeXFwcdXmFCqW9tFmkiC6aC7U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/mnt/c/Users/MASTER/Desktop/projects/solana/solana_my_project/gif_portal/myepicproject/id.json+"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
